---
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    env_file: .env # use .env
    network_mode: host #optional
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=CET #optional
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - UPDATE_IP=ipv4 #optional
      - LOG_FILE=true #optional
    volumes:
      - ${DOCKER_PATH}/duckdns/config:/config #optional
    restart: always
