version: '3'

networks:
  media-network:
    name: media-network
    driver: bridge
    ipam:
      driver: default

services:
  gluetun:
    restart: always
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - ${PORT_GLUETUN_HTTP}:6881
      - ${PORT_GLUETUN_HTTP}:6881/udp
      - ${PORT_QBIT_HTTP}:8085 # qbittorrent
      - ${PORT_RADARR_HTTP}:7878 # Radarr
      - ${PORT_SONARR_HTTP}:8989 # Sonarr
      - ${PORT_PROWLARR_HTTP}:9696 # Prowlarr
      - ${PORT_JELLYSEERR_HTTP}:5055 # Jellyseerr
      - ${PORT_JELLYFIN1_ACCESS}:8096 #jellyfin1
      - ${PORT_READARR_HTTP}:8787 #readarr
      - ${PORT_JELLYFIN2_HTTP}:8920 #optional jellyfin2
      - ${PORT_JELLYFIN3_HTTP}:7359/udp #optional jellyfin3
      - ${PORT_JELLYFIN4_HTTP}:1900/udp #optional jellyfin4

    volumes:
      - ${DOCKER_PATH}/arr-stack:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_PORT_FORWARDING=on
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${OPENVPN_COUNTRY}
      # Timezone for accurate log times
      - TZ=${TZ}
      # Server list updater
    networks:
      - media-network
  ###
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: 'service:gluetun'
    environment:
      - PUID=${ID}
      - PGID=${ID}
      - TZ=${TZ}
      - WEBUI_PORT=8085
    volumes:
      - ${DOCKER_PATH}/arr-stack/qbittorrent:/config
      - ${DOCKER_MEDIA}/Downloads:/downloads
    depends_on:
      - gluetun
    restart: always
    healthcheck:
      test: 'curl -sfI -o /dev/null --connect-timeout 10 --retry 3 --retry-delay 10 --retry-all-errors https://www.google.com/robots.txt || kill 1'
      interval: 1m
      timeout: 1m
  ###
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: 'service:gluetun'
    environment:
      - PUID=${ID}
      - PGID=${ID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_PATH}/arr-stack/sonarr/data:/config
      - ${DOCKER_MEDIA}/Shows:/shows #optional
      - ${DOCKER_MEDIA}/Downloads:/downloads #optional
      - ${DOCKER_MEDIA}/:/media
    depends_on:
      - gluetun
    restart: always
    healthcheck:
      test: 'curl -sfI -o /dev/null --connect-timeout 10 --retry 3 --retry-delay 10 --retry-all-errors https://www.google.com/robots.txt || kill 1'
      interval: 1m
      timeout: 1m
  ###
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: 'service:gluetun'
    environment:
      - PUID=${ID}
      - PGID=${ID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_PATH}/arr-stack/radarr/data:/config
      - ${DOCKER_MEDIA}/Movies:/movies #optional
      - ${DOCKER_MEDIA}/Downloads:/downloads #optional
      - ${DOCKER_MEDIA}/:/media
    depends_on:
      - gluetun
    restart: always
    healthcheck:
      test: 'curl -sfI -o /dev/null --connect-timeout 10 --retry 3 --retry-delay 10 --retry-all-errors https://www.google.com/robots.txt || kill 1'
      interval: 1m
      timeout: 1m
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    network_mode: 'service:gluetun'
    depends_on:
      - gluetun
    environment:
      - PUID=${ID}
      - PGID=${ID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_PATH}/arr_stack/readarr/:/config
      - ${DOCKER_MEDIA}/Books/:/books #optional
      - ${DOCKER_MEDIA}/Audiobooks/:/audiobooks #optional
      - ${DOCKER_MEDIA}/Downloads:/downloads #optional
    restart: always
    healthcheck:
      test: 'curl -sfI -o /dev/null --connect-timeout 10 --retry 3 --retry-delay 10 --retry-all-errors https://www.google.com/robots.txt || kill 1'
      interval: 1m
      timeout: 1m
  ###
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: 'service:gluetun'
    environment:
      - PUID=${ID}
      - PGID=${ID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_PATH}/arr-stack/prowlarr/data:/config
    depends_on:
      - gluetun
    restart: always
    healthcheck:
      test: 'curl -sfI -o /dev/null --connect-timeout 10 --retry 3 --retry-delay 10 --retry-all-errors https://www.google.com/robots.txt || kill 1'
      interval: 1m
      timeout: 1m
  ###
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    volumes:
      - ${DOCKER_PATH}/arr-stack/jellyseerr:/app/config
    environment:
      - PUID=${ID}
      - PGID=${ID}
      - TZ=${TZ}
    network_mode: 'service:gluetun'
    depends_on:
      - gluetun
    restart: always
    healthcheck:
      test: 'curl -sfI -o /dev/null --connect-timeout 10 --retry 3 --retry-delay 10 --retry-all-errors https://www.google.com/robots.txt || kill 1'
      interval: 1m
      timeout: 1m
  ###
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: 'service:gluetun'
    environment:
      - PUID=${ID}
      - PGID=${ID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_PATH}/jellyfin/library:/config
      - ${DOCKER_MEDIA}/Shows:/data/tvshows
      - ${DOCKER_MEDIA}/Movies:/data/movies
      - ${DOCKER_MEDIA}/Anime:/data/anime
      - ${DOCKER_MEDIA}/Course:/data/course
      - ${DOCKER_MEDIA}/:/media
    restart: always
    depends_on:
      - gluetun
    healthcheck:
      test: 'curl -sfI -o /dev/null --connect-timeout 10 --retry 3 --retry-delay 10 --retry-all-errors https://www.google.com/robots.txt || kill 1'
      interval: 1m
      timeout: 1m
