version: '3.8'
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, pt, chs, cht)
      - LANG=en
      # ?? Required:
      # Change this to your host's public address
      - WG_HOST=${WG_HOST}
      # Optional:
      - 'PASSWORD=${WG_PASSWORD}'
      - WG_PORT=${PORT_WGEASY_HTTP}
      # - WG_DEFAULT_ADDRESS=10.13.13.*
      - WG_DEFAULT_DNS=1.1.1.2,1.0.0.2
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=0.0.0.0/0
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ${DOCKER_PATH}/wg-easy:/etc/wireguard
    ports:
      - ${PORT_WGEASY_HTTP}:51820/udp
      - 51821:51821/tcp
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - default
networks:
  default:
    name: nginx_default
    external: true
