---
version: '3'
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - ${DOCKER_PATH}/homarr/configs:/app/data/configs
      - ${DOCKER_PATH}/homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${PORT_HOMARR_HTTP}:7575
    networks:
      - default
networks:
  default:
    name: nginx_default
    external: true
