version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${DOCKER_PATH}/nginx/data:/data
      - ${DOCKER_PATH}/nginx/letsencrypt:/etc/letsencrypt
