version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - ${PORT_NGINX_HTTP}:80
      - ${PORT_NGINX_HTTPS}:81
      - ${PORT_NGINX_PANEL}:443
    volumes:
      - ${DOCKER_PATH}/nginx/data:/data
      - ${DOCKER_PATH}/nginx/letsencrypt:/etc/letsencrypt
