version: '3'

services:
  vikunja:
    image: vikunja/vikunja
    environment:
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: ${VIKUNJA_DB_MYSQLPW}
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: ${VIKUNJA_DB_SQLUSER}
      VIKUNJA_DATABASE_DATABASE: ${VIKUNJA_DB_SQLUSER}
      VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_JWTSECRET}
    ports:
      - ${PORT_VIKUNJA_HTTP}:3456
    volumes:
      - ${DOCKER_PATH}/vikunja:/app/vikunja/files
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - default
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${VIKUNJA_DB_MYSQLPW}
      POSTGRES_USER: ${VIKUNJA_DB_SQLUSER}
      PGDATA: /tmp
    volumes:
      - ${DOCKER_PATH}/postgres/vikunja:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U $$POSTGRES_USER']
      interval: 2s
    networks:
      - default
networks:
  default:
    name: nginx_default
    external: true
