---
services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${ID} #optional
      - PGID=${ID} #optional
      - TZ=${TZ}
      #- FIREFOX_CLI=https://www.linuxserver.io/ #optional
    volumes:
      - ${DOCKER_PATH}/firefox:/config
    ports:
      - ${PORT_FIREFOXVNC_HTTP}:3000
      - ${PORT_FIREFOX_HTTP}:3001
    shm_size: '2gb'
    restart: unless-stopped
    networks:
      - default
networks:
  default:
    name: nginx_default
    external: true
