---
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=${ID} #optional
      - PGID=${ID} #optional
      - TZ=${TZ}
    volumes:
      - ${DOCKER_PATH}/freshrss/config:/config
    ports:
      - ${PORT_FRESHRSS_HTTP}:80
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    name: nginx_default
    external: true
