version: '3'

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=${ID}
      - PGID=${ID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_PATH}/config:/config
      - ${DOCKER_BACKUP_PATH}/Syncthing:/data
      - ${DOCKER_BACKUP_PATH}/SyncthingBackup:/backupdata
    ports:
      - ${PORT_SYNCTHING_HTTP}:8384
      - '22000:22000/tcp'
      - '22000:22000/udp'
      - '21027:21027/udp'
    restart: always
    networks:
      - default
networks:
  default:
    name: nginx_default
    external: true
