version: '3'

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - ${DOCKER_PATH}/config:/config
      - ${BACKUP_PATH}/Syncthing:/data
      - ${BACKUP_PATH}/SyncthingBackup:/backupdata
    ports:
      - '8384:8384'
      - '22000:22000/tcp'
      - '22000:22000/udp'
      - '21027:21027/udp'
    restart: always
